<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <style>
        @import "/styles.css" screen;
    </style>
    <title>Advertisment board</title>
</head>
<body>
    <div class="container">
        <?php foreach ($ads as $ad): ?>
            <div class="ad">
                <div><?=$ad->getId()?></div>
                <div><?=$ad->getAdText()?></div>
                <div><?=$ad->getName()?></div>
                <div><?=$ad->getPassword()?></div>
                <div><?=$ad->getPhone()?></div>
                <div><?=$ad->getPostDate()?></div>
            </div>
            <br>
        <?php endforeach?>
    </div>
</body>
</html>
