<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Make new advertisement</title>
</head>
<body>
    <div class="container">
        <div class="back-to-main">
            <a href="/?page=<?= $prevPage ?>"><< Return</a>
        </div>
        <header class="header">
            <h1>Make new advertisement</h1>
        </header>
        <main class="main">
            <form action="/adform" method="post" class="form-group">
                <div class="post-form">
                    <div class="post-form__item post-form__ad-text">
                        <label>
                            <div>Advertisement text:</div>
                            <textarea name="ad[ad-text]" required class="form-control"></textarea>
                        </label>
                    </div>
                    <div class="post-form__item post-form__name">
                        <label>
                            <div>Your name:</div>
                            <input type="text" name="ad[user-name]" required class="form-control">
                        </label>
                    </div>
                    <div class="post-form__item post-form__phone">
                        <label>
                            <div>Your password for this ad:</div>
                            <input type="password" name="ad[password]" required class="form-control">
                        </label>
                    </div>
                    <div class="post-form__item post-form__phone">
                        <label>
                            <div>Your phone:</div>
                            <input type="text" name="ad[phone]" required class="form-control">
                        </label>
                    </div>
                    <div class="post-form__item post-form__button">
                        <input type="submit" value="Post advertisement" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </main>
    </div>
</body>
</html>
