<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="reset.css">
    <link rel="stylesheet" href="styles.css">
    <title>Make new advertisement</title>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>Make new advertisement</h1>
        </header>
        <main class="main">
            <form action="/new-ad-post" method="post">
                <div class="post-form">
                    <div class="post-form__item post-form__ad-text">
                        <div>Advertisement text:</div>
                        <textarea name="ad[ad-text]"></textarea>
                    </div>
                    <div class="post-form__item post-form__name">
                        <div>Your name:</div>
                        <input type="text" name="ad[user-name]">
                    </div>
                    <div class="post-form__item post-form__phone">
                        <div>Your password for this ad:</div>
                        <input type="password" name="ad[password]">
                    </div>
                    <div class="post-form__item post-form__phone">
                        <div>Your phone:</div>
                        <input type="text" name="ad[phone]">
                    </div>
                    <div class="post-form__item post-form__button">
                        <input type="submit" value="Post advertisement">
                    </div>
                </div>
            </form>
        </main>
    </div>
</body>
</html>
