
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Advertisement</title>
</head>
<body>
    <div class="container">
        <div class="back-to-main">
            <a href="/?page=<?= $prevPage ?>"><< Return</a>
        </div>
        <header class="header">
            <h1>Advertisement <?=$ad->getId()?></h1>
        </header>
        <main class="detailed-ad">
            <div>Text</div>
            <div><?=$ad->getAdText()?></div>
            <div>Name</div>
            <div><?=$ad->getUserName()?></div>
            <div>Phone</div>
            <div><?=$ad->getPhone()?></div>
            <div>Post date</div>
            <div><?=$ad->getPostDate()?></div>
            <div>
                <form action="/edit-form/<?=$ad->getId()?>" method="get">
                    <input type="submit" value="Edit" class="btn btn-secondary">
                </form>
            </div>
            <div>
                <form action="/delete-form/<?=$ad->getId()?>" method="get">
                    <input type="submit" value="Delete" class="btn btn-danger">
                </form>
            </div>
        </main>
    </div>
</body>
</html>
