
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../reset.css">
    <link rel="stylesheet" href="../styles.css">
    <title>Advertisement</title>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>Advertisement <?=$ad->getId()?></h1>
        </header>
        <main class="detailed-ad">
            <div>Text</div>
            <div><?=$ad->getAdText()?></div>
            <div>Name</div>
            <div><?=$ad->getUserName()?></div>
            <div>Phone</div>
            <div><?=$ad->getPhone()?></div>
            <div>Post date</div>
            <div><?=$ad->getPostDate()?></div>
            <div>
                <form action="/edit-form/<?=$ad->getId()?>" method="get">
                    <input type="submit" value="Edit">
                </form>
            </div>
            <div>
                <form action="/delete-form/<?=$ad->getId()?>" method="get">
                    <input type="submit" value="Delete">
                </form>
            </div>
        </main>
    </div>
</body>
</html>
